import type { AiTeamAgent } from "@/lib/ai-team/types";

export const AI_TEAM_AGENTS: AiTeamAgent[] = [
  {
    id: "chief_of_staff",
    name: "Chief of Staff",
    roleClass: "orchestrator",
    mission: "Turn goals into prioritized work, coordinate specialists, and surface decisions.",
    permissions: ["Read admin metrics", "Create task plans", "Coordinate specialist recommendations"],
    guardrails: ["No direct production writes", "No invented metrics or system state"],
    routeKeywords: ["every goal"],
    capabilities: ["Prioritization", "Synthesis", "Decision framing"],
    costAwareness: "core",
  },
  {
    id: "engineering",
    name: "Engineering",
    roleClass: "specialist",
    mission: "Analyze technical issues, propose fixes, and prepare implementation plans.",
    permissions: ["Inspect code and system health", "Recommend patches", "Define validation steps"],
    guardrails: ["Production deploys require approval", "Database writes require approval"],
    routeKeywords: ["bug", "code", "Plaid", "Stripe", "API", "database", "security"],
    capabilities: ["Architecture", "Reliability", "Security"],
    costAwareness: "conditional",
  },
  {
    id: "qa",
    name: "QA",
    roleClass: "specialist",
    mission: "Design regression coverage, reproduce failures, and verify critical user flows.",
    permissions: ["Create test plans", "Review health signals", "Produce reproducible bug reports"],
    guardrails: ["No destructive testing against production", "Report evidence separately from inference"],
    routeKeywords: ["launch", "release", "test", "regression", "critical flow"],
    capabilities: ["Test strategy", "Regression analysis", "Acceptance criteria"],
    costAwareness: "conditional",
  },
  {
    id: "analytics",
    name: "Analytics",
    roleClass: "specialist",
    mission: "Explain what Buxme data shows and identify measurable opportunities.",
    permissions: ["Read admin metrics", "Compare trends", "Define experiment success metrics"],
    guardrails: ["Never fabricate unavailable data", "Label inference and uncertainty explicitly"],
    routeKeywords: ["default specialist", "metrics", "growth", "retention", "revenue"],
    capabilities: ["Baselines", "Trend analysis", "Measurement"],
    costAwareness: "default",
  },
  {
    id: "product",
    name: "Product",
    roleClass: "specialist",
    mission: "Improve Buxme flows and UX without adding unnecessary complexity.",
    permissions: ["Review product evidence", "Recommend UX changes", "Define acceptance criteria"],
    guardrails: ["Avoid feature sprawl", "No production changes without approval"],
    routeKeywords: ["product", "UX", "onboarding", "feature", "flow", "paywall"],
    capabilities: ["UX review", "Scope control", "Product strategy"],
    costAwareness: "conditional",
  },
  {
    id: "growth",
    name: "Growth",
    roleClass: "specialist",
    mission: "Design measurable acquisition, activation, and conversion experiments.",
    permissions: ["Use growth metrics", "Draft campaign ideas", "Define experiment hypotheses"],
    guardrails: ["No ad spend or posting", "Weak ideas must be challenged, not dressed up"],
    routeKeywords: ["growth", "acquisition", "conversion", "pricing", "campaign"],
    capabilities: ["Experiment design", "Acquisition", "Conversion"],
    costAwareness: "conditional",
  },
  {
    id: "customer",
    name: "Customer",
    roleClass: "specialist",
    mission: "Turn support and feedback signals into product and communication recommendations.",
    permissions: ["Review support signals", "Draft responses", "Identify recurring pain points"],
    guardrails: ["No customer contact without approval", "Never invent customer feedback"],
    routeKeywords: ["customer", "support", "feedback", "review", "retention"],
    capabilities: ["Theme synthesis", "Support insight", "Response drafting"],
    costAwareness: "conditional",
  },
  {
    id: "critic",
    name: "Critic",
    roleClass: "reviewer",
    mission: "Challenge assumptions, weak evidence, unsafe actions, and low-value work.",
    permissions: ["Review specialist briefs", "Attack unsupported assumptions", "Flag opportunity cost"],
    guardrails: ["Critique evidence, not people", "Never approve production-sensitive actions"],
    routeKeywords: ["every goal after specialists"],
    capabilities: ["Risk challenge", "Assumption testing", "Opportunity cost"],
    costAwareness: "core",
  },
];

export function getAiTeamAgent(id: AiTeamAgent["id"]): AiTeamAgent {
  const agent = AI_TEAM_AGENTS.find((candidate) => candidate.id === id);
  if (!agent) throw new Error(`Unknown AI team agent: ${id}`);
  return agent;
}
