import type { AiTeamToolRecord } from "@/lib/ai-team/types";

export const AI_TEAM_CAPABILITIES: readonly AiTeamToolRecord[] = [
  {
    id: "operating-evidence",
    label: "Operating evidence",
    description: "Reads bounded admin, revenue, product, Plaid, and health signals.",
    riskClass: "read",
    connected: true,
    available: true,
    approvalRequired: false,
  },
  {
    id: "mission-memory",
    label: "Mission memory",
    description: "Stores safe lifecycle events, verification, and final reports.",
    riskClass: "normal_write",
    connected: true,
    available: true,
    approvalRequired: false,
  },
  {
    id: "execution-staging",
    label: "Execution staging",
    description: "Creates approval-gated packets for an external operator.",
    riskClass: "sensitive_write",
    connected: true,
    available: true,
    approvalRequired: true,
  },
  {
    id: "screen-permission",
    label: "Screen sharing permission",
    description: "Explicit browser screen-share permission with local preview and instant off.",
    riskClass: "read",
    connected: true,
    available: true,
    approvalRequired: true,
  },
  {
    id: "screen-intelligence",
    label: "Screen intelligence",
    description: "Sends one founder-approved frame to the configured AI runtime; the Buxme app does not persist the screenshot.",
    riskClass: "read",
    connected: true,
    available: true,
    approvalRequired: true,
  },
  {
    id: "filesystem-shell",
    label: "Filesystem / shell executor",
    description: "No unrestricted local command or filesystem executor is connected.",
    riskClass: "destructive",
    connected: false,
    available: false,
    approvalRequired: true,
  },
  {
    id: "external-publishing",
    label: "External publishing",
    description: "No public posting, email sending, or deployment executor is connected.",
    riskClass: "external",
    connected: false,
    available: false,
    approvalRequired: true,
  },
  {
    id: "payments",
    label: "Payments",
    description: "No payment, subscription, or financial action executor is connected.",
    riskClass: "financial",
    connected: false,
    available: false,
    approvalRequired: true,
  },
  {
    id: "security-control",
    label: "Security controls",
    description: "No permission, credential, or security-setting executor is connected.",
    riskClass: "security",
    connected: false,
    available: false,
    approvalRequired: true,
  },
] as const;
