import type { FinanceData } from "./types";

export const sampleFinanceData: FinanceData = {
  accounts: [
    {
      id: "acc-checking-001",
      name: "Checking",
      institution: "Chase",
      type: "checking",
      balance: 5_200,
      monthlyChange: 220,
    },
    {
      id: "acc-savings-001",
      name: "Savings",
      institution: "Chase",
      type: "savings",
      balance: 3_000,
      monthlyChange: 200,
    },
    {
      id: "acc-asset-001",
      name: "Home Equity",
      institution: "Primary Residence",
      type: "investment",
      balance: 37_500,
      monthlyChange: -620,
    },
  ],
  bills: [
    {
      id: "bill-rent-001",
      name: "Rent",
      amount: 1_800,
      dueDay: 1,
      autopay: true,
      recurring: true,
      category: "Housing",
      paidMonth: "2026-06",
    },
    {
      id: "bill-utilities-001",
      name: "Utilities",
      amount: 180,
      dueDay: 15,
      autopay: true,
      recurring: true,
      category: "Housing",
      paidMonth: "2026-06",
    },
    {
      id: "bill-groceries-001",
      name: "Groceries",
      amount: 600,
      dueDay: 0,
      autopay: false,
      recurring: true,
      category: "Food",
      paidMonth: null,
    },
    {
      id: "bill-subscriptions-001",
      name: "Subscriptions",
      amount: 85,
      dueDay: 10,
      autopay: true,
      recurring: true,
      category: "Lifestyle",
      paidMonth: "2026-06",
    },
    {
      id: "bill-insurance-001",
      name: "Insurance",
      amount: 320,
      dueDay: 20,
      autopay: true,
      recurring: true,
      category: "Insurance",
      paidMonth: null,
    },
    {
      id: "bill-transportation-001",
      name: "Transportation",
      amount: 400,
      dueDay: 0,
      autopay: false,
      recurring: true,
      category: "Transport",
      paidMonth: null,
    },
    {
      id: "bill-dining-001",
      name: "Dining",
      amount: 295,
      dueDay: 0,
      autopay: false,
      recurring: false,
      category: "Food",
      paidMonth: null,
    },
    {
      id: "bill-phone-001",
      name: "Phone",
      amount: 500,
      dueDay: 5,
      autopay: true,
      recurring: true,
      category: "Utilities",
      paidMonth: "2026-06",
    },
  ],
  income: [
    {
      id: "income-salary-001",
      name: "Salary",
      amount: 5_400,
      frequency: "monthly",
      category: "Employment",
    },
    {
      id: "income-freelance-001",
      name: "Freelance",
      amount: 1_000,
      frequency: "monthly",
      category: "Side Income",
    },
  ],
  savingsGoals: [
    {
      id: "goal-emergency-001",
      name: "Emergency Fund",
      type: "emergency_fund",
      icon: "🛡️",
      current: 8_200,
      target: 15_000,
      createdAt: "2025-01-15T00:00:00.000Z",
    },
    {
      id: "goal-vacation-001",
      name: "Vacation",
      type: "vacation",
      icon: "✈️",
      current: 2_400,
      target: 5_000,
      createdAt: "2025-03-01T00:00:00.000Z",
    },
    {
      id: "goal-laptop-001",
      name: "New Laptop",
      type: "custom",
      icon: "💻",
      current: 900,
      target: 2_000,
      createdAt: "2025-05-10T00:00:00.000Z",
    },
  ],
  debts: [
    {
      id: "debt-credit-001",
      name: "Credit Card",
      balance: 4_250,
      originalBalance: 6_000,
      interestRate: 22.4,
      minimumPayment: 150,
      monthlyChange: -200,
      dueDay: 12,
      accountType: "credit_card",
    },
    {
      id: "debt-auto-001",
      name: "Auto Loan",
      balance: 14_500,
      originalBalance: 22_000,
      interestRate: 5.9,
      minimumPayment: 320,
      monthlyChange: -450,
      dueDay: 18,
      accountType: "auto_loan",
    },
  ],
  investments: [
    {
      id: "inv-brokerage-001",
      name: "Brokerage",
      value: 62_430,
      monthlyChange: 1_200,
      monthlyContribution: 200,
      type: "Taxable",
    },
    {
      id: "inv-index-001",
      name: "Index Funds",
      value: 35_200,
      monthlyChange: 690,
      monthlyContribution: 100,
      type: "ETF",
    },
  ],
  transactions: [],
  events: [],
};
